=== Ser87ch/SABS_proj_rft/xml/settings/generation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:annotation>
		<xs:documentation>Настройки генерации документов
		</xs:documentation>
	</xs:annotation>
	<xs:element name="PacketEPD">
		<xs:complexType>

			<xs:choice maxOccurs="unbounded">

				<xs:element name="ED101" type="attr" />
				<xs:element name="ED103" type="attr" />
				<xs:element name="ED104" type="attr" />
				<xs:element name="ED105" type="attr" />
				<xs:element name="ED108" type="attr" />
			</xs:choice>
			<xs:attribute name="EDAuthor" type="xs:string" use="required" />
			<xs:attribute name="EPDNo" type="xs:string" use="required" />
			<xs:attribute name="EDFirstNo" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:complexType name="attr">
		<xs:annotation>
			<xs:documentation>Реквизиты документа</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Payer" type="client">
				<xs:annotation>
					<xs:documentation>Плательщик</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Payee" type="client">
				<xs:annotation>
					<xs:documentation>Получатель</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="Quantity" type="xs:string" use="required" />
	</xs:complexType>
	<xs:complexType name="client">
		<xs:annotation>
			<xs:documentation>Клиенты</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="BIC" type="strAttr" />
			<xs:element name="PersonalAcc" type="strAttr" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="strAttr">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="row" type="xs:string" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== Ser87ch/SABS_proj_rft/xml/settings/generation.xml
<PacketEPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="generation.xsd" EDAuthor="4582002000" EPDNo="100" EDFirstNo="100">
	<ED101 Quantity="2">
		<Payer>
			<BIC>@</BIC>
			<PersonalAcc><![CDATA[select top 1 NUM_ACC from dbo.Account where rest = (select min(rest) from dbo.Account where substring(NUM_ACC,1,1) = '4' and substring(NUM_ACC,1,5) <> '40101')]]></PersonalAcc>			    
		</Payer>
		<Payee>
		    <BIC><![CDATA[select top 3 NEWNUM from dbo.BNKSEEK where substring(NEWNUM,1,4) = substring('@', 1, 4) and UER in ('2','3','4','5') and NEWNUM <> '@']]></BIC>
		    <PersonalAcc>40702810000000000005</PersonalAcc>
		</Payee>
	</ED101>
	<ED101 Quantity="2">
		<Payer>
			<BIC>@</BIC>
			<PersonalAcc><![CDATA[select top 1 NUM_ACC from dbo.Account where rest = (select min(rest) from dbo.Account where substring(NUM_ACC,1,1) = '4' and substring(NUM_ACC,1,5) <> '40101')]]></PersonalAcc>			    
		</Payer>
		<Payee>
		    <BIC row="2"><![CDATA[select top 3 NEWNUM from dbo.BNKSEEK where substring(NEWNUM,1,4) = substring('@', 1, 4) and UER in ('2','3','4','5') and NEWNUM <> '@']]></BIC>
		    <PersonalAcc>40702810000000000005</PersonalAcc>
		</Payee>
	</ED101>
	<ED101 Quantity="2">
		<Payer>
			<BIC>@</BIC>
			<PersonalAcc><![CDATA[select top 1 NUM_ACC from dbo.Account where rest = (select min(rest) from dbo.Account where substring(NUM_ACC,1,1) = '4' and substring(NUM_ACC,1,5) <> '40101')]]></PersonalAcc>			    
		</Payer>
		<Payee>
		    <BIC row="3"><![CDATA[select top 3 NEWNUM from dbo.BNKSEEK where substring(NEWNUM,1,4) = substring('@', 1, 4) and UER in ('2','3','4','5') and NEWNUM <> '@']]></BIC>
		    <PersonalAcc>40702810000000000005</PersonalAcc>
		</Payee>
	</ED101>
</PacketEPD>
